name: Build and deploy container app to Azure Web App - pacientecare-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: List target folder
        run: ls -al target

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://pacientecareregistry.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_2ec3daff3c6949279c37ce619f89efb3 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_22311d5c848b436db0c1b42dc54391b2 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: pacientecareregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2ec3daff3c6949279c37ce619f89efb3 }}/pacientecare-app:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pacientecare-app'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_367fcd54c5824850bce79bcdfbda7be3 }}
          images: 'pacientecareregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2ec3daff3c6949279c37ce619f89efb3 }}/pacientecare-app:${{ github.sha }}'
